### ISSUE TITLE
ACMEv1 protocol obsolete

### ISSUE THREAD

**Issue by BHMath** [BradJonesLLC/docker-haproxy-letsencrypt#10]
Hi,

Just received this email from lets encrypt

> Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail. For most people, simply upgrading to
the latest version of your existing client will suffice. You can view the
client list at: https://letsencrypt.org/docs/client-options/

Can you upgrade your container please ?

**Comment by bradjones1** [comment]
This project is unmaintained and there are much better options out there; consider [Traefik](https://github.com/containous/traefik), for instance.
